services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=booking
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
      - redis

  webserver:
    image: nginx:alpine
    container_name: booking-webserver
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    container_name: booking-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: booking
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - booking_mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"

  redis:
    image: redis:alpine
    container_name: booking-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: booking-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  booking_mysql_data:
    driver: local
